name: auto_route_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  auto_route: ^7.8.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  
flutter:

  uses-material-design: true
